CREATE DATABASE TEST AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY US PAGESIZE 4096;
CONNECT TO TEST;

CREATE TABLE TESTTABLE (
  NAME VARCHAR(20) NOT NULL,
  AGE INTEGER NOT NULL,
  LOCATION VARCHAR(20)
);
